friends/src/accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'

urlpatterns = [
	url(r'^$', views.profile_view, name='index'),
	url(r"^activate/$", views.activateAccount_view, name='activate'),
	url(r"^change-password/$", views.passwordChange_view, name='change-password'),
	url(r"^forgot-password/$", views.passwordForgot_view, name='forgot-password'),
	url(r'^update/$', views.update_view, name='edit'),
	url(r'^login/$', views.userLogin_view, name='login'),
	url(r'^logout/$', views.userLogout_view, name='logout'),
	url(r'^register/$', views.userCreate_view, name='create'),
	url(r'^(?P<username>[a-z0-9._]+)/$', views.publicProfile_view, name='public-profile'),
]

friends/src/friends/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from main import views


urlpatterns = [
	url(r'^$', views.home_view, name='homepage'),
	url(r'^404-not-found/$', views.ErrorNotFound_view, name='404NotFound'),
	url('admin/', admin.site.urls),
	url(r'^accounts/', include('accounts.urls')),
	url(r'^comments/', include('comments.urls')),
	url(r'^contact-us/$', views.contactUs_view, name='contact-us'),
	url(r'^notifications/$', views.notifications_view, name='notifications'),
	url(r'^notifications/(?P<pk>[0-9]+)/$', views.notificationStatus_view, name='notf-seen'),
	url(r'^posts/', include('posts.urls')),
	url(r'^search/$', views.search_view, name='search'),
	url(r'^valildatename/$', views.valildateName_view, name='valildate-name'),
	url(r'^valildateemail/$', views.valildateEmail_view, name='valildate-email'),
	url(r'^valildatepassword/$', views.valildatePassword_view, name='valildate-password'),

]

"""
if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
"""

friends/src/posts/urls.py
from django.conf.urls import url
from . import views
app_name = 'posts'

urlpatterns = [
	url(r'^$', views.postList_view, name='list'),
	url(r'^create/$', views.createPost_view, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', views.detail_view, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_view, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_view, name='delete'),
    url(r'^(?P<slug>[\w-]+)/like/$', views.like_view, name='like'),
]

friends/src/notifications/models.py
from django.db import models
from accounts.models import Account
from posts.models import Post
from django.shortcuts import reverse


class Notification(models.Model):
	account = models.ForeignKey(Account, on_delete=models.CASCADE)
	post    = models.ForeignKey(Post, on_delete=models.CASCADE)
	content = models.TextField()
	is_seen = models.BooleanField(default=False, blank=True)
	created = models.DateTimeField(auto_now=False, auto_now_add=True)

	def get_seen_status_link(self):
		return reverse('notf-seen', kwargs={'pk': self.pk})

	
	class Meta:
		ordering = ['-created']

	def __str__(self):
		return str(self.account.user.username) + " - " + str(self.content) 

friends/src/notifications/views.py
from django.shortcuts import render

# Create your views here.

friends/src/templates/contact.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Contact Us</title>
<meta charset="utf-8">
<link rel="shortcut icon" type="image/png" href="{% static 'images/logo.png' %}"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Zeta Template Project - Contact">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/fontawesome-free-5.0.1/css/fontawesome-all.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/js-flickr-gallery-1.24/js-flickr-gallery.css' %}">
<link href="{% static 'plugins/colorbox/colorbox.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact_responsive.css' %}">


</head>

<body>

<div class="super_container">
	
	<!-- Header -->
	<header class="header d-flex flex-row justify-content-end align-items-center">
		<!-- Logo -->
		<div class="logo_container mr-auto">
			<div class="logo">
				<a href="{% url 'homepage' %}"><span>F</span>Friends<span></span></a>
			</div>
		</div>
		<!-- Main Navigation -->
		<nav class="main_nav justify-self-end">
			<ul class="nav_items">
				<li class="{% if request.path == '/' %}active{% endif%}"><a href="{% url 'homepage' %}"><span>home</span></a></li>
                <li class="{% if '/posts/' in request.path %}active{% endif%}"><a href="{% url 'posts:list' %}"><span>blog</span></a></li>
				{% if request.user.is_authenticated %}
					<li class="{% if request.path == '/notifications/' %}active{% endif %}">
						<a href="{% url 'notifications' %}">
							<span class="fa fa-bullhorn"> [{{NOTFS_COUNT}}]</span>
						</a>
					</li>
					<li class="{% if request.path == '/accounts/' %}active{% endif %}">
						<a href="{% url 'accounts:index' %}"><span>Profile</span></a>
					</li>
					<li class="{% if request.path == '/contact-us/' %}active{% endif %}" >
						<a href="{% url 'contact-us' %}"><span>contact</span></a>
					</li>
					<li>
						<a href="{% url 'accounts:logout' %}?next={{ request.path }}"><span>Log Out</span></a>
					</li>
				{% else %}
					<li class="{% if request.path == '/accounts/register/' or request.path == '/accounts/login/' %}active{% endif %}" ><a href="{% url 'accounts:login' %}?next={{ request.path }}" class=""><span>Register/Login</span></a></li>
					<li class="{% if request.path == '/contact-us/' %}active{% endif %}" ><a href="{% url 'contact-us' %}"><span>contact</span></a></li>
				{% endif %}

			</ul>
		</nav>

		<!-- Hamburger -->
		<div class="hamburger_container">
			<span class="hamburger_text">Menu</span>
			<span class="hamburger_icon"></span>
		</div>

	</header>

	<!-- Menu -->
	<div class="fs_menu_overlay"></div>
	<div class="fs_menu_container">
		<div class="fs_menu_shapes"><img src="{% static 'images/menu_shapes.png' %}" alt=""></div>
		<nav class="fs_menu_nav">
			<ul class="fs_menu_list">
				<li><a href="{% url 'homepage' %}"><span><span>H</span>Home</span></a></li>
				<li><a href="{% url 'posts:list' %}"><span><span>B</span>Blog</span></a></li>
				<li><a href="{% url 'contact-us' %}"><span><span>C</span>Contact</span></a></li>
				{% if request.user.is_authenticated %}
					<li class="{% if request.path == '/notifications/' %}active{% endif %}">
						<a href="{% url 'notifications' %}">
							<span class="fa fa-bullhorn"> [{{NOTFS_COUNT}}]</span>
						</a>
					</li>
					<li><a href="{% url 'accounts:index' %}"><span><span>P</span>Profile</span></a></li>
					<li><a href="{% url 'accounts:logout' %}?next={{ request.path }}"><span><span>L</span>Log Ou</span>t</a></li>
				{% else %}
					<li class="{% if request.path == '/users/register/' or request.path == '/users/login/' %}active{% endif %}" ><a href="{% url 'accounts:login' %}?next={{ request.path }}" class=""><span><span>R</span>Register/Login</span></a></li>
				{% endif %}
			</ul>
		</nav>
		<div class="fs_social_container d-flex flex-row justify-content-end align-items-center">
			<ul class="fs_social">
				<li><a href="https://www.facebook.com/r.kabir2011/" target="_blank"><i class="fab fa-facebook-f trans_300"></i></a></li>
				<li><a href="https://twitter.com/iamrk_" target="_blank"><i class="fab fa-twitter trans_300"></i></a></li>
				<li><a href="https://github.com/iraihankabir" target="_blank"><i class="fab fa-github trans_300"></i></a></li>
				<li><a href="https://www.youtube.com/channel/UCmPcUtSFNcN7n4Piv2HgtgA" target="_blank"><i class="fab fa-youtube trans_300"></i></a></li>
			</ul>
		</div>
	</div>

	<!-- Home -->

	<div class="home prlx_parent">

		<!-- Parallax Background -->
		<div class="home_background prlx" style="background-image:url({% static 'images/blog_background.jpg' %})"></div>
		<div class="services_page_shapes" style="background-image:url({% static 'images/services_page_shapes.png' %})"></div>

		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="home_content">
						<h1>Contact</h1>
						<span>get in touch</span>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Contact Content -->

	<div class="contact_content bg-success">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<div class="contact_main_content">

						<div class="contact_subtitle">contact us</div>
						{% if error != "" %}
							<div class="alert alert-warning offset-sm-1 text-center  mt-2 mb-2 alert-dismissible fade show" role="alert">
					            {{ error }}
					            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					                <span aria-hidden="true">&times;</span>
					            </button>
					        </div>
						{% endif %}	

						{% if messages %}
					        <div class="alert alert-success offset-sm-1 text-center  mt-2 mb-2 alert-dismissible fade show" role="alert">
					            {% for message in messages %}
					                <li>{{ message|safe }}</li>
					            {% endfor %}
					            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					                <span aria-hidden="true">&times;</span>
					            </button>
					        </div>
						{% endif %}					
						<!-- Contact Us Form -->
						<div class="contact_form_container">
							<form id="reply_form" method="post" action="">{% csrf_token %}
								<div>
									<input name="name" id="contact_form_name" class="input_field contact_form_name" type="text" placeholder="Name" required="required" data-error="Name is required.">
									<input id="contact_form_email" name="email" class="input_field contact_form_email" type="email" placeholder="E-mail" required="required" data-error="Valid email is required.">
									<input name="subject" id="contact_form_subject" class="input_field contact_form_subject" type="text" placeholder="Subject" required="required" data-error="Subject is required.">
									<textarea name="message" id="contact_form_message" class="text_field contact_form_message"  placeholder="Message" rows="4" required data-error="Please, write us a message."></textarea>
								</div>
								<div>
									<button id="contact_form_submit" type="submit" class="contact_submit_btn trans_300" value="Submit">
										send<img src="{% static 'images/arrow_right.svg' %}" alt="">
									</button>
								</div>

							</form>
						</div>

					</div>
				</div>
				
				<!-- Sidebar -->
				<div class="col-lg-4">
					<div class="contact_sidebar">
						
						<!-- Contact Info -->
						<div class="sidebar_section">
							<div class="sidebar_contact_info">
								<div class="sidebar_title">contact info</div>
								<ul>
									<span class="text-white font-weight-bold">RAIHAN KABIR</span>
									<li>Madar Bux Hall, University of Rajshahi</li>
									<li>iraihankabir@yahoo.com</li>
									<li>+8801 521 11 6643</li>
								</ul>
							</div>
						</div>

					</div>
				</div>

			</div>

			<!-- Google Map Container -->

			<div class="row">
				<div class="contact_subtitle mt-5"></span> Location</div>
				<div  class="col-12">
					<div id="google_map " >
						<div class="map_container">
							<div id="map" style="border: 5px solid white">
								<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3634.3722432034897!2d88.6354386!3d24.3683508!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39fbf02db6d04b59%3A0xaa58eb411ea3ec5c!2sUniversity+of+Rajshahi!5e0!3m2!1sen!2sbd!4v1533388513520" style="height: 100%; width: 100%" frameborder="0" style="border:0" allowfullscreen></iframe>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>

	

	<!-- Footer -->
	<footer class="footer">
		<div class="container">
			<div class="row footer_content d-flex flex-sm-row flex-column align-items-center">
				<div class="col-sm-6 cr text-sm-left text-center">
					<p>
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | RaihanKabir</p>
				</div>
				<div class="col-sm-6 text-sm-right text-center">
					<div class="footer_social_container">
						<ul class="footer_social">
							<li><a href="https://www.facebook.com/r.kabir2011/" target="_blank"><i class="fab fa-facebook-f trans_300"></i></a></li>
							<li><a href="https://twitter.com/iamrk_" target="_blank"><i class="fab fa-twitter trans_300"></i></a></li>
							<li><a href="https://github.com/iraihankabir" target="_blank"><i class="fab fa-github trans_300"></i></a></li>
							<li><a href="https://www.youtube.com/channel/UCmPcUtSFNcN7n4Piv2HgtgA" target="_blank"><i class="fab fa-youtube trans_300"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/progressbar/progressbar.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/js-flickr-gallery-1.24/js-flickr-gallery.js' %}"></script>
<script src="{% static 'plugins/colorbox/jquery.colorbox-min.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'js/blog_custom.js' %}"></script>

</body>

</html>

friends/src/templates/notification.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Notifications{% endblock title %}

{% block slider %}
    <div style="margin-top: 160px!important"></div>
{% endblock slider %}
{% block post %}{% endblock post %}
{% block content %}
    <div class="container mb-5 mt-3 pb-5 min_height_400">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="text-center">
                    <a href="{% url 'accounts:login' %}">
                        <h2 class="text-center font-weight-bold active btn btn-md btn-danger">
                            NOTIFICATIONS
                        </h2>
                    </a>
                </div>
                <hr>
            </div>
        </div>


        <div class="row">
            <div class="col-md-3"></div>
            <div id="error" class="col-md-6"></div>
        </div>
        <div class="row">
            {% if NOTFS %}
                {% csrf_token %}
                {% for notification in NOTFS %}
                    {% if notification.is_seen == False %}
                        <div class="col-sm-8 offset-sm-2 col-md-6 offset-md-3">
                            <p class="bg-light p-2 text-info"><a  href="{{notification.get_seen_status_link}}">{{notification.content}}
                            </a><br>
                            - <small><i>{{notification.created|timesince}} ago</i></small>
                            </p>
                        </div>
                    {% endif %}
                {% endfor %}
                {% for notification in NOTFS %}
                    {% if notification.is_seen == True %}
                        <div class="col-sm-8 offset-sm-2 col-md-6 offset-md-3">
                            <p class="bg-light p-2"><a  href="{{notification.post.get_absolute_url}}">{{notification.content}}
                            </a><br>
                            - <small><i>{{notification.created|timesince}} ago</i></small>
                            </p>
                        </div>
                        <hr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="col-12 text-center text-danger font-weight-bold">No notifications!</div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block js_files %}
    <script type="text/javascript">
        $(document).ready(function(){
            
        });
    </script>
{% endblock js_files %}

friends/src/templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}FRIENDS - Search{% endblock title %}

{% block slider %}
    <div style="margin-top: 120px!important"></div>
{% endblock slider %}
{% block post %}{% endblock post %}
{% block content %}
    <div class="container min_height_500 mb-5 mt-3 pb-5 min_height_400">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="text-center">
                    <div class="text-center mb-3">
                        <img src="{% static 'images/logo.png' %}" class="img-fluid" style="height: 80px;">
                    </div>
                    <a href="{% url 'accounts:login' %}">
                        <h2 class="text-center font-weight-bold active btn btn-md btn-danger">
                            SEARCH ENGINE
                        </h2>
                    </a>
                </div>
                <hr>
            </div>
        </div>

        <div class="row">
            <!-- Search -->
            <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                <!--<form action="{% url 'search' %}" method="get">-->
                    {% csrf_token %}
                    <div>
                        <input id="blog_search" name="q" value="{{query}}" type="search" placeholder="enter keywords" class="form-control">
                        <button id="search_submit" type="submit" class="search_submit_btn trans_300" value="Submit">
                            <img src="{% static 'images/search.png' %}" alt="">
                        </button>
                    </div>
                <!--</form>-->

                <!-- RESULT -->
                <ul class="list-group list_style_none m-2" style="display: none;" id="searchResult"></ul>
            </div>
        </div>
    </div>
{% endblock content %}


{% block js_files %}
    <script type="text/javascript">
        function jQuerySearch(){
            var query = $('#blog_search').val();
            if( query.length > 0 ){
                $.ajax({
                    type: 'POST',
                    url: "{% url 'search' %}",
                    data:{
                        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                        query: query,
                    },
                    success: function(data){
                        $('#searchResult').fadeIn(100);
                        $('#searchResult').html(data);
                    },
                });
            }
        }
        $(document).ready(function(){
            var value = $('#blog_search').val();
            if( value.length > 0 ){
                jQuerySearch();
            }
            $('#blog_search').keyup(function(){
                jQuerySearch();
            });
        });
    </script>
{% endblock js_files %}