friends/src/accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'

urlpatterns = [
	url(r'^$', views.profile_view, name='index'),
	url(r"^activate/$", views.activateAccount_view, name='activate'),
	url(r"^change-password/$", views.passwordChange_view, name='change-password'),
	url(r"^forgot-password/$", views.passwordForgot_view, name='forgot-password'),
	url(r'^update/$', views.update_view, name='edit'),
	url(r'^login/$', views.userLogin_view, name='login'),
	url(r'^logout/$', views.userLogout_view, name='logout'),
	url(r'^register/$', views.userCreate_view, name='create'),
	url(r'^(?P<username>[a-z0-9._]+)/$', views.publicProfile_view, name='public-profile'),
]

friends/src/comments/urls.py
from django.conf.urls import url
from . import views
app_name = 'comments'

urlpatterns = [
	url(r'^create/$', views.create_view, name='create'),
	url(r'^reply-create/$', views.replyCreate_view, name='reply-create'),
	url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_view, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_view, name='delete'),
]

friends/src/friends/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from main import views


urlpatterns = [
	url(r'^$', views.home_view, name='homepage'),
	url(r'^404-not-found/$', views.ErrorNotFound_view, name='404NotFound'),
	url('admin/', admin.site.urls),
	url(r'^accounts/', include('accounts.urls')),
	url(r'^comments/', include('comments.urls')),
	url(r'^contact-us/$', views.contactUs_view, name='contact-us'),
	url(r'^notifications/$', views.notifications_view, name='notifications'),
	url(r'^notifications/(?P<pk>[0-9]+)/$', views.notificationStatus_view, name='notf-seen'),
	url(r'^posts/', include('posts.urls')),
	url(r'^search/$', views.search_view, name='search'),
	url(r'^valildatename/$', views.valildateName_view, name='valildate-name'),
	url(r'^valildateemail/$', views.valildateEmail_view, name='valildate-email'),
	url(r'^valildatepassword/$', views.valildatePassword_view, name='valildate-password'),

]

"""
if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
"""

friends/src/posts/urls.py
from django.conf.urls import url
from . import views
app_name = 'posts'

urlpatterns = [
	url(r'^$', views.postList_view, name='list'),
	url(r'^create/$', views.createPost_view, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', views.detail_view, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_view, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_view, name='delete'),
    url(r'^(?P<slug>[\w-]+)/like/$', views.like_view, name='like'),
]

friends/src/posts/models.py
from django.db import models
from accounts.models import Account
from django.shortcuts import reverse
from django.db.models.signals import pre_save
from main.utils import unique_slug_generator
from django.utils.text import slugify
from django.db.models import Q




class PostQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            lookup = (Q(content__icontains=query))
            qs = qs.filter(lookup).distinct()
        return qs

class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)
    
    






class Post(models.Model):
    account  = models.ForeignKey(Account, on_delete=models.CASCADE)
    slug     = models.SlugField(unique=True, blank=True, null=True)
    content  = models.TextField()
    photo1   = models.ImageField(upload_to="posts/",
                      null=True,
                      blank=True,
                      width_field="width_field1",
                      height_field="height_field1",
                    )
    drive_photo1_link = models.CharField(max_length=1000, default='', blank=True, null=True)
    height_field1 = models.IntegerField(default=0)
    width_field1 = models.IntegerField(default=0)

    photo2   = models.ImageField(upload_to="posts",
                      null=True,
                      blank=True,
                      width_field="width_field2",
                      height_field="height_field2",
                    )
    drive_photo2_link = models.CharField(max_length=1000, default='', blank=True, null=True)
    height_field2 = models.IntegerField(default=0)
    width_field2 = models.IntegerField(default=0)

    photo3   = models.ImageField(upload_to="posts",
                      null=True,
                      blank=True,
                      width_field="width_field3",
                      height_field="height_field3",
                    )
    drive_photo3_link = models.CharField(max_length=1000, default='', blank=True, null=True)
    height_field3 = models.IntegerField(default=0)
    width_field3 = models.IntegerField(default=0)
    likes = models.PositiveIntegerField(default=0, blank=True)
    comments = models.PositiveIntegerField(default=0, blank=True)
    is_active  = models.BooleanField(default=True, blank=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)



    objects = PostManager()


    def __str__(self):
        return str(self.account.user.first_name) + ' - ' + str(self.slug)

    @property
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    @property
    def get_edit_url(self):
        return reverse('posts:edit', kwargs={'slug': self.slug})
    
    @property
    def get_delete_url(self):
        return reverse('posts:delete', kwargs={'slug': self.slug})
    class Meta:
        ordering = ['-created']

def pre_save_action(sender, instance, *args, **kwargs):
    content = instance.content
    if len(content) <= 40:
        slug = content
    else:
        slug = content[:40]
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, new_slug=slugify(slug))

pre_save.connect(pre_save_action, sender=Post)

friends/src/posts/forms.py
from django import forms

class postEditForm(forms.Form):
    content = forms.CharField(
        required=True,
        label='',
        widget=forms.Textarea(
            attrs={
                'Placeholder': 'Explain your problem...',
                'class': 'form-control mb-2',
                'id': 'content',
                'style': 'height: 180px;'
            }
        )
    )
    def __init__(self, post, *args, **kwargs):
        super(postEditForm, self).__init__(*args, **kwargs)
        self.initial['content'] = post.content

    def clean(self, *args, **kwargs):
        content = self.cleaned_data.get('content')
        if content is None or len(content) == 0:
            raise forms.ValidationError("Content can't be blank.")
        return super(postEditForm, self).clean(*args, **kwargs)


class postForm(forms.Form):
    content = forms.CharField(
        required=False,
        label='',
        widget=forms.Textarea(
            attrs={
                'Placeholder': 'Explain your problem...',
                'class': 'form-control mb-2',
                'id': 'content',
                'style': 'height: 180px;'
            }
        )
    )

    photo1 = forms.ImageField(label='', required=False)
    photo2 = forms.ImageField(label='', required=False)
    photo3 = forms.ImageField(label='', required=False)
    photo1.widget.attrs['id'] = 'inPhoto1'
    photo1.widget.attrs['style'] = 'display:none;'

    photo2.widget.attrs['id'] = 'inPhoto2'
    photo2.widget.attrs['style'] = 'display:none;'

    photo3.widget.attrs['id'] = 'inPhoto3'
    photo3.widget.attrs['style'] = 'display:none;'
    def clean(self, *args, **kwargs):
        content = self.cleaned_data.get('content')
        if content is None or len(content) == 0:
            raise forms.ValidationError("Write something to post.")
        return super(postForm, self).clean(*args, **kwargs)

friends/src/posts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import Post
from .forms import postForm
from django.contrib.auth.decorators import login_required
from accounts.models import Account, User
from django.contrib import messages
from .forms import postForm, postEditForm
from comments.models import Comment
from likes.models import Like
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from notifications.models import Notification
import os
from main.utils import uploadToGoogleDrive






@login_required
def like_view(request, slug):
    if request.method == "POST":
        post = Post.objects.get(slug=slug)
        account = Account.objects.get(user=request.user)
        qs = Like.objects.filter(post=post).filter(account=account)
        if not qs.exists():
            like = Like()
            like.account = account
            like.post = post
            like.save()
            post.likes += 1
            post.save()
            if like.account != post.account:
                notf = Notification()
                notf.account = post.account
                notf.post = post
                content = like.account.user.first_name + ' ' + like.account.user.last_name + ' liked  your post.'
                notf.content = content
                notf.save()
        else:
            like = Like.objects.get(post=post, account=account)
            like.delete()
            post.likes -= 1
            post.save()
        return HttpResponseRedirect(post.get_absolute_url)
    return HttpResponseRedirect('/posts/')

@login_required
def delete_view(request, slug):
    template_name = 'posts/confirm-delete.html'
    try:
        post = Post.objects.get(slug=slug)
    except:
        return redirect('/posts/')

    if post.account.user != request.user:
        messages.warning(request, "You are not authorized to perform the action.")
        return HttpResponseRedirect('/posts/')

    if request.method == 'POST':
        if request.POST.get('response') == 'yes':
            post.delete()
            messages.success(request, 'Post has been deleted successfully.')
            return HttpResponseRedirect('/posts/')
        else:
            messages.success(request, "Something went wrong. Couldn't delete the post")
            return HttpResponseRedirect(post.get_absolute_url)
    contex = {
        'post': post,
    }
    return render(request, template_name, contex)



@login_required
def edit_view(request, slug):
    template_name = 'posts/edit.html'
    try:
        post = Post.objects.get(slug=slug)
    except:
        return HttpResponseRedirect('/posts/')

    if post.account.user != request.user:
        messages.warning(request, "You are not authorized to perform the action.")
        return HttpResponseRedirect('/posts/')
    form = postEditForm(post, request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post.content = form.cleaned_data.get('content')
            post.save()
            messages.success(request, 'Post has been updated successfully.')
            return HttpResponseRedirect(post.get_edit_url)
    contex = {
        'form': form,
        'post': post
    }
    return render(request, template_name, contex)


def detail_view(request, slug):
    template_name = 'posts/detail.html'
    account = None
    if request.user.is_authenticated:
        account = Account.objects.get(user=request.user)
    try:
        post     = Post.objects.get(slug=slug)
        comments = Comment.objects.all().filter(post=post).filter(parent__isnull=True)
        likes    = Like.objects.all().filter(post=post)
    except:
        return redirect('/posts/')
    posts = Post.objects.all().filter(is_active=True)

    liked = False
    for like in likes:
        if account == like.account:
            liked = True
    contex = {
        'post': post,
        'posts': posts,
        'comments': comments,
        'likes': likes,
        'liked': liked
    }
    return render(request, template_name, contex)

def postList_view(request):
    post_list = Post.objects.all().filter(is_active=True)
    paginator = Paginator(post_list, 5)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    template_name = 'posts/blog.html'
    contex = {
        'posts': posts,
        'form': postForm(),
        'comments': Comment.objects.all().filter(is_active=True)
    }
    return render(request, template_name, contex)

@login_required
def createPost_view(request):
    template_name = 'posts/create.html'
    form = postForm(request.POST or None, request.FILES or None, auto_id=False)
    if request.method == "POST":
        if form.is_valid():
            photo1 = form.cleaned_data.get('photo1')
            photo2 = form.cleaned_data.get('photo2')
            photo3 = form.cleaned_data.get('photo3')
            post = Post()
            post.account = Account.objects.get(user=request.user)
            post.content = form.cleaned_data.get('content')
            if photo1 != '' and photo1 != None:
                post.photo1 = photo1
            if photo2 != '' and photo2 != None:
                post.photo2 = photo2
            if photo3 != '' and photo3 != None:
                post.photo3 = photo3
            post.save()
            
            # uploading photo1
            if post.photo1 and os.path.exists(post.photo1.path):
                drive_id = uploadToGoogleDrive(post.photo1.path, 'POST')
            if drive_id != "":
                post.drive_photo1_link = "https://drive.google.com/thumbnail?id=" + str(drive_id)

            # uploading photo2
            if post.photo2 and os.path.exists(post.photo2.path):
                drive_id = uploadToGoogleDrive(post.photo2.path, 'POST')
            if drive_id != "":
                post.drive_photo2_ink = "https://drive.google.com/thumbnail?id=" + str(drive_id)

            # uploading photo3
            if post.photo3 and os.path.exists(post.photo3.path):
                drive_id = uploadToGoogleDrive(post.photo3.path, 'POST')
            if drive_id != "":
                post.drive_photo3_link = "https://drive.google.com/thumbnail?id=" + str(drive_id)
            post.save()



            messages.success(request, 'Your post has been uploaded successfully.')
            return HttpResponseRedirect(post.get_absolute_url)
    contex = {
        'form': form
    }
    return render(request, template_name, contex)

friends/src/templates/posts/confirm-delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Post Delete{% endblock title %}

{% block slider %}
    <div style="margin-top: 120px!important"></div>
{% endblock slider %}
{% block post %}{% endblock post %}

{% block content %}
<div class="super_container">
    <div class="container min_height_500">
        <div class="mt-5 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <p class="text-success">{{ post.content }}</p>
            <p class="alert-link">Are you sure you want to delete this post permanently?</p>
            <form action="" method="post">{% csrf_token %}
                <input type="hidden" name="slug" value="{{ post.slug }}">
                <input type="hidden" name="response" value="yes">
                <button type="submit" class="btn btn-md btn-danger">Delete</button>
                <a href="{{ post.get_absolute_url }}" class="btn btn-md btn-success">Cancel</a>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

friends/src/templates/posts/detail.html
{% extends 'posts/blog.html' %}
{% load staticfiles %}
{% block extra_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles/blog_post_styles.css' %}">
{% endblock %}
{% block title %}{{ post.content|truncatechars:60 }}{% endblock title %}
{% block create_post %}{% endblock create_post %}


{% block content %}
<!-- Blog Content -->
<div class="blog_content bg-light">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="blog_main_content">
                    <!-- Blog Post -->
					<article class="blog_post">
						<div class="date_box d-flex flex-column align-items-center justify-content-center">
							<span>{{ post.created|date }}</span>
						</div>
						<div class=" text-right">
							{% if request.user.is_authenticated and request.user == post.account.user %}
					            <a href="{{ post.get_delete_url }}" class=" mr-1 btn btn-sm btn-danger"><span class="text-white fa fa-trash"></span></a>
					            <a href="{{ post.get_edit_url }}" class="btn btn-sm btn-success"><span class="text-white fa fa-edit"></span></a>
					        {% endif %}
				        </div>
						<h3 class="blog_post_title"><a href="{{ post.account.get_public_profile_link}}">{{ post.account.user.get_full_name }}</a></h3>
						<div class="blog_post_meta">
							<span class="blog_post_author">Edited: {{ post.updated|date }}</span>
							<span class="blog_post_comments">{{post.comments}} comments</span>
						</div>
						{% if post.drive_photo1_link != '' %}
							<div class="blog_post_image mb-2">
								<div class="blog_post_image_background" style="background-image:url({{post.drive_photo1_link}})"></div>
							</div>
						{% endif %}
						{% if post.drive_photo2_link != '' %}
							<div class="blog_post_image mb-2">
								<div class="blog_post_image_background" style="background-image:url({{post.drive_photo2_link}})"></div>
							</div>
						{% endif %}
						{% if post.drive_photo3_link != '' %}
							<div class="blog_post_image mb-2">
								<div class="blog_post_image_background" style="background-image:url({{post.drive_photo3_link}})"></div>
							</div>
						{% endif %}
						<div class="blog_post_text text-justify mt-2">
							<p>{{ post.content|safe }}</p>
						</div>
						<hr>
						<!-- COMMENT FORM -->
						{% if request.user.is_authenticated %}
							<div class="blog_post_reply mt-5 ">
								<form id="reply_form" action="{% url 'comments:create' %}" method="post">{% csrf_token %}
									<input type="hidden" name="slug" value="{{ post.slug }}">
									<div>
										<textarea id="comment" class="text_field reply_form_message" name="comment"  placeholder="Write a comment..." rows="4" required data-error="Please, write a comment."></textarea>
									</div>
									<div class="text-right">
										<button id="reply_form_submit" type="submit" class="btn btn-sm mt-2 btn-primary trans_300">
											<span class="fa fa-paper-plane"></span> Comment
										</button>
									</div>
								</form>
							</div>
						{% endif %}
						<!-- Blog Post Comments -->
						<div class="blog_post_comments mt-0">
							<div class="blog_post_subtitle comments_subtitle">comments</div>
							
							<!-- Comments -->
							<div class="blog_post_comments_container">
								{% if comments %}
									{% for comment in comments %}
									<!-- Comment -->
									<div class="blog_post_comment d-flex flex-row">
										<div class="blog_post_comment_image">
											{% if comment.account.photo %}
												<img src="{{comment.account.photo.url}}" alt="">
											{% else %}
												<img src="{% static 'images/blog_1.jpg' %}" alt="">
											{% endif %}
										</div>
										<div class="blog_post_comment_content">
											{% if request.user.is_authenticated and request.user == comment.account.user %}
												<div class="mb-3">
													<a href="{{comment.get_delete_url}}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
													<a href="{{comment.get_edit_url}}" class="btn btn-sm  btn-success"><span class="fa fa-edit"></span></a>
												</div>
											{% endif %}
											<div class="blog_post_comment_meta">
												<div class="blog_post_comment_name"><a href="{{comment.account.get_public_profile_link}}">{{comment.account.user.get_full_name}}</a></div>
												<div class="blog_post_comment_date">{{comment.created|timesince}} ago</div>
											</div>
											
											<div class="blog_post_comment_text">
												<p>{{comment.content}}</p>
											</div>


											<div class="text-center">
												<a href="#" data-toggle="collapse" data-target="#collapsedReplies{{comment.pk}}" class="blog_post_link text-danger mb-4 mt-2 font-weight-bold" data-toggle="dropdown" >replies ({{comment.replies.all.count}})</a>
											</div>



											<!-- REPLIES -->
											<div class="collapse" id="collapsedReplies{{comment.pk}}">
												<div class="blog_post_reply mt-0 ">
													<form id="reply_form" action="{% url 'comments:reply-create' %}" method="post">{% csrf_token %}
														<input type="hidden" name="post_slug" value="{{post.slug}}">
														<input type="hidden" name="parent_id" value="{{comment.id}}">
														<div>
															<textarea id="reply" class="text_field reply_form_message" name="reply"  placeholder="Write a reply" rows="4" required data-error="Please, write a reply."></textarea>
														</div>
														<div class="text-right">
															<button id="reply_form_submit" type="submit" class="btn btn-sm mt-2 btn-primary trans_300">Reply</button>
														</div>
													</form>
												</div>
												{% for reply in comment.replies.all %}										
													<div class="blog_post_comment d-flex flex-row">
														<div class="blog_post_reply_content">
															{% if request.user.is_authenticated and request.user == reply.account.user %}
																<div class="mb-3">
																	<a href="{{reply.get_delete_url}}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
																	<a href="{{reply.get_edit_url}}" class="btn btn-sm  btn-success"><span class="fa fa-edit"></span></a>
																</div>
															{% endif %}
															<div class="blog_post_comment_meta">
																<div class="blog_post_comment_name"><a href="{{reply.account.get_public_profile_link}}"><small class="font-weight-bold text-dark">{{reply.account.user.get_full_name}}</small></a></div>
																<div class="blog_post_comment_date"><small>{{reply.created|timesince}} ago</small></div>
															</div>
															
															<div class="blog_post_comment_text">
																<p><small>{{reply.content}}</small></p>
															</div>
														</div>
													</div>
													<hr>
												{% endfor %}<!-- REPLIES -->
											</div>
										</div>
									</div> <!-- Comment -->	
									<hr>


									{% endfor %}
								{% endif %}
							</div><!-- Comment -->
						</div>
						
					</article>
				</div>
			</div>

			<!-- Sidebar -->
			<div class="col-lg-4">
				<div class="blog_sidebar">

					<!-- Search -->
					<div class="sidebar_section">
						<div class="sidebar_search">
							<form action="{% url 'search' %}" method="post">{% csrf_token %}
								<div id="search_form" class="search_form">
									<input id="blog_search" name="q" type="search" placeholder="enter keywords" required="required" data-error="Valid keywords required.">
									<button id="search_submit" type="submit" class="search_submit_btn trans_300" value="Submit">
										<img src="{% static 'images/search.png' %}" alt="">
									</button>
								</div>
							</form>
						</div>
					</div>

					<!-- Recent Posts -->
					<div class="sidebar_section">
						<div class="sidebar_recent">
							<div class="sidebar_title">recent posts</div>

							<!-- Recent Post -->
							{% for post in posts %}
                                {% if forloop.counter < 5 %}
                                    <div class="recent_post d-flex flex-row justify-content-start">
                                        <div class="recent_post_image">
                                            {% if post.drive_photo1_link != '' %}
                                                <a href="{{ post.get_absolute_url }}"><img class="side_post_photo" src="{{ post.drive_photo1_link }}" alt=""></a>
                                            {% else %}
                                                <a href="{{ post.get_absolute_url }}"><img class="side_post_photo" src="{% static 'images/logo.png' %}" alt=""></a>
                                            {% endif %}
                                        </div>
                                        <div class="recent_post_content">
                                            <h4 class="recent_post_title"><a href="">{{ post.content|truncatechars_html:20 }}</a></h4>
                                            <span class="recent_post_date">{{ post.created|date }}</span>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
						</div>
					</div>
					<!-- Tabs -->
					<div class="sidebar_section">
						<div class="sidebar_tabs">

							<!-- Tabs Nav -->
							<div class="tabs_container">
								<ul class="tabs">
									<li class="tab active" data-active-tab="tab_1"><span>popular</span></li>
									<li class="tab" data-active-tab="tab_2"><span>comments</span></li>
								</ul>
							</div>

							<!-- Tab Containers -->
							<div id="tab_1" class="tab_container active">

								<!-- Popular -->
								<div class="sidebar_popular">
									{% if posts %}
										{% for post in posts %}
											{% if forloop.counter < 5 %}
												<!-- Popular Post -->
												<div class="popular_post d-flex flex-row justify-content-start">
													<div class="popular_post_image">
														{% if post.drive_photo1_link != '' %}
															<a href="{{ post.get_absolute_url}}"><img src="{{ post.drive_photo1_link }}" class="side_post_photo" alt=""></a>
														{% else %}
															<a href="{{ post.get_absolute_url}}"><img src="{% static 'images/logo.png' %}" class="side_post_photo" alt=""></a>
														{% endif %}
													</div>
													<div class="popular_post_content">
														<h4 class="popular_post_title"><a href="{{post.get_absolute_url}}">{{post.content|truncatechars_html:20}}</a></h4>
														<span class="popular_post_date">{{post.created|date}}</span>
													</div>
												</div>
											{% endif %}
										{% endfor %}
									{% endif %}
								</div>
							</div>

							<div id="tab_2" class="tab_container">

								<!-- Comments -->
								<div class="sidebar_comments">

									{% if comments %}
										{% for comment in comments %}
											{% if forloop.counter < 6 %}
											<!-- Comment -->
											<div class="comment d-flex flex-row justify-content-start">
												<div class="comment_icon">
													<i class="far fa-comment"></i>
												</div>
												<div class="comment_content">
													<p class="comment_text">{{comment.content}}</p>
													<div class="comment_meta">
														<span>by {{comment.account.user.first_name}}</span>
														<span>{{comment.created|date}}</span>
													</div>
												</div>
											</div>
											{% endif %}
										{% endfor %}
									{% endif %}
								</div>
							</div>

						</div>
					</div>

					<!-- Gallery -->

					<div class="sidebar_section">
						<div class="sidebar_gallery">
							<div class="sidebar_title">gallery</div>

							<ul class="gallery_items">

								<!-- Gallery Item -->
								<li class="gallery_item">
									<a href="{% static 'images/gallery_1_large.jpg' %}">
										<img src="{% static 'images/gallery_1.jpg' %}" alt="">
									</a>
								</li>

                                <!-- Gallery Item -->
								<li class="gallery_item">
									<a href="{% static 'images/gallery_2_large.jpg' %}">
										<img src="{% static 'images/gallery_2.jpg' %}" alt="">
									</a>
								</li>

                                <!-- Gallery Item -->
								<li class="gallery_item">
									<a href="{% static 'images/gallery_3_large.jpg' %}">
										<img src="{% static 'images/gallery_3.jpg' %}" alt="">
									</a>
								</li>

                                <!-- Gallery Item -->
								<li class="gallery_item">
									<a href="{% static 'images/gallery_4_large.jpg' %}">
										<img src="{% static 'images/gallery_4.jpg' %}" alt="">
									</a>
								</li>

                                <!-- Gallery Item -->
								<li class="gallery_item">
									<a href="{% static 'images/gallery_5_large.jpg' %}">
										<img src="{% static 'images/gallery_5.jpg' %}" alt="">
									</a>
								</li>

                                <li class="gallery_item">
									<a href="{% static 'images/gallery_6_large.jpg' %}">
										<img src="{% static 'images/gallery_6.jpg' %}" alt="">
									</a>
								</li>
							</ul>
						</div>
					</div>

					<!-- Quote -->

					<div class="sidebar_section">
						<div class="sidebar_quote">
							<div class="sidebar_title">quote of the day</div>
							<p>No self is of itself alone. It has a long chain of intellectual ancestors. The "I" is chained to ancestry by many factors… This is not mere allegory, but an eternal memory</p>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
{% endblock content %}

friends/src/templates/posts/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Edit Post{% endblock title %}

{% block slider %}
    <div style="margin-top: 130px!important"></div>
{% endblock slider %}
{% block post %}{% endblock post %}


{% block content %}
<div class="super_container">
	<!-- Page Top -->
	<div class="home prlx_parent">
		<div class="container">
			<div class="row">
				<div class="col-md-6 offset-md-3">
                    <div class="text-center mb-3">
                        <img src="{% static 'images/logo.png' %}" class="img-fluid" style="height: 80px;">
                    </div>
                    <div class="text-center">
                        <a href="{% url 'accounts:login' %}">
                            <h2 class="font-weight-bold text-center active btn btn-md btn-success">
                                EDIT POST
                            </h2>
                        </a>
                    </div>
                    <hr>
                </div>
			</div>
		</div>
	</div>

	<!-- Blog Content -->

	<div class="blog_content min_height_400">
		<div class="container">
			<div class="row">
				<div class="col-md-8 offset-md-2">
					<div class="blog_main_content">
                        <article class="blog_post mt-2 p-2" style="border-radius: 10px">
                            <form action="" method="post">{% csrf_token %}
                                {{ form.as_p }}
                                <div>
                                    <button class="btn btn-md btn-success">
                                        <span class="fa fa-paper-plane"></span> Update
                                    </button>
                                </div>
                            </form>
                            <div class="text-right">
                            	<a class="font-weight-bold" href="{{ post.get_absolute_url }}"><< Back to post</a>
                            </div>
                        </article>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}