friends/src/accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'

urlpatterns = [
	url(r'^$', views.profile_view, name='index'),
	url(r"^activate/$", views.activateAccount_view, name='activate'),
	url(r"^change-password/$", views.passwordChange_view, name='change-password'),
	url(r"^forgot-password/$", views.passwordForgot_view, name='forgot-password'),
	url(r'^update/$', views.update_view, name='edit'),
	url(r'^login/$', views.userLogin_view, name='login'),
	url(r'^logout/$', views.userLogout_view, name='logout'),
	url(r'^register/$', views.userCreate_view, name='create'),
	url(r'^(?P<username>[a-z0-9._]+)/$', views.publicProfile_view, name='public-profile'),
]

friends/src/friends/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from main import views


urlpatterns = [
	url(r'^$', views.home_view, name='homepage'),
	url(r'^404-not-found/$', views.ErrorNotFound_view, name='404NotFound'),
	url('admin/', admin.site.urls),
	url(r'^accounts/', include('accounts.urls')),
	url(r'^comments/', include('comments.urls')),
	url(r'^contact-us/$', views.contactUs_view, name='contact-us'),
	url(r'^notifications/$', views.notifications_view, name='notifications'),
	url(r'^notifications/(?P<pk>[0-9]+)/$', views.notificationStatus_view, name='notf-seen'),
	url(r'^posts/', include('posts.urls')),
	url(r'^search/$', views.search_view, name='search'),
	url(r'^valildatename/$', views.valildateName_view, name='valildate-name'),
	url(r'^valildateemail/$', views.valildateEmail_view, name='valildate-email'),
	url(r'^valildatepassword/$', views.valildatePassword_view, name='valildate-password'),

]

"""
if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
"""

friends/src/posts/urls.py
from django.conf.urls import url
from . import views
app_name = 'posts'

urlpatterns = [
	url(r'^$', views.postList_view, name='list'),
	url(r'^create/$', views.createPost_view, name='create'),
	url(r'^(?P<slug>[\w-]+)/$', views.detail_view, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.edit_view, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete_view, name='delete'),
    url(r'^(?P<slug>[\w-]+)/like/$', views.like_view, name='like'),
]

friends/src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from main.utils import get_random_number
from django.shortcuts import reverse
from django.db.models import Q



class Account(models.Model):
    user 			= models.OneToOneField(User, on_delete=models.CASCADE)
    photo 			= models.ImageField(
        upload_to="profile_photos/",
        null=True,
        blank=True,
        width_field="width_field",
        height_field="height_field",
    )
    drive_photo_link= models.CharField(max_length=1000, default='', blank=True, null=True)
    height_field    = models.IntegerField(default=0)
    width_field     = models.IntegerField(default=0)

    is_active       = models.BooleanField(default=True)

    activation_code = models.CharField(max_length=10, blank=True, null=True)
    activation_time = models.DateTimeField(auto_now=False, auto_now_add=True)

    forgotpass_code = models.CharField(max_length=10, blank=True, null=True)

    recover_code    = models.CharField(max_length=10, blank=True, null=True)
    recover_time    = models.DateTimeField(blank=True, null=True)

    about_me	    = models.TextField(default='', blank=True)






    def __str__(self):
        return self.user.email + ' - ' + self.user.get_full_name()


    def get_profile_link(self):
        return reverse('accounts:index')

    def get_public_profile_link(self):
        return reverse('accounts:public-profile', kwargs={'username': self.user.username})


def pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.activation_code:
		instance.activation_code = get_random_number(size=6)
	if not instance.forgotpass_code:
		instance.forgotpass_code = get_random_number(size=4)
	if not instance.recover_code:
		instance.recover_code = get_random_number(size=6)

pre_save.connect(pre_save_receiver, sender=Account)

friends/src/accounts/forms.py
from django import forms
from main.validators import validateName, validUsername


class passwordChangeForm(forms.Form):
    user = None
    current = forms.CharField(
        required=True,
        label="Current", validators=[],
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Current password'}),
    )

    new = forms.CharField(
        required=True,
        label="New", validators=[],
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'New password'}),
    )

    re_new = forms.CharField(
        required=True,
        label="Confirm", validators=[],
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm password'}),
    )

    def __init__(self, user, *args, **kwargs):
        super(passwordChangeForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean(self, *args, **kwargs):
        current = self.cleaned_data.get('current')
        new = self.cleaned_data.get('new')
        re_new = self.cleaned_data.get('re_new')
        if not self.user.check_password(raw_password=current):
            raise forms.ValidationError("Incorrect current password.")
        if len(new) < 6 or len(re_new) < 6:
            raise forms.ValidationError('Too short password.')
        if new != re_new:
            raise forms.ValidationError("Password didn't match.")
        else:
            print(self.user.check_password(raw_password=current))
        return super(passwordChangeForm, self).clean(*args, **kwargs)


class UpdateForm(forms.Form):
    photo      = forms.ImageField(label='', required=False)
    first_name = forms.CharField(
        required=True,
        label="First Name", validators=[],
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First name'}),
    )
    last_name = forms.CharField(
        required=True,
        label="Last Name", validators=[],
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last name'}),
    )

    about_me = forms.CharField(
        required=False,
        label="About me", validators=[],
        widget=forms.Textarea(
            attrs={
                'class': 'form-control', 'placeholder': 'Write about you...',
                'style': 'height:180px',
            }
        ),
    )
    photo.widget.attrs['style'] = "display:none"
    photo.widget.attrs['id'] = "inPhoto"
    def __init__(self, account, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.initial['first_name'] = account.user.first_name
        self.initial['last_name'] = account.user.last_name
        self.initial['about_me'] = account.about_me

    def clean(self, *args, **kwargs):
        first_name = self.cleaned_data.get('first_name')
        last_name  = self.cleaned_data.get('last_name')
        if validateName(first_name) != '' or validateName(last_name) != '':
            msg = validateName(first_name)
            raise forms.ValidationError('<li>Name contains invalid character.</li><li>Name is too short.</li>')
        return super(UpdateForm, self).clean(*args, **kwargs)

friends/src/accounts/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.http import HttpResponse
from .models import Account, User
from django.contrib.auth import authenticate , login, logout
from django.contrib import messages
from main.validators import *
from main.utils import usernameGenerator, get_random_password, get_random_number, uploadToGoogleDrive
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .forms import UpdateForm, passwordChangeForm
from posts.models import Post
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os



def publicProfile_view(request, username):
    template_name = 'accounts/public_profile.html'

    qs = User.objects.filter(username=username)
    if qs.exists():
        user      = User.objects.get(username=username)
        account   = Account.objects.get(user=user)
        post_list = Post.objects.all().filter(account=account).filter(is_active=True)
    else:
        msg = username + ' is not associated with any account!'
        messages.warning(request, msg)
        return HttpResponseRedirect('/404-not-found/')

    paginator = Paginator(post_list, 5) # posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    contex = {
        'account': account,
        'posts': posts
    }

    return render(request, template_name, contex)






def passwordForgot_view(request):
    template_name = 'accounts/forgot-password.html'
    email = request.GET.get('email', None)
    code = None
    message = ""
    if email != None:
        qs = User.objects.filter(email=email)
        if qs.exists():
            account = Account.objects.get(user=User.objects.get(email=email))
            code = account.forgotpass_code
        else:
            message = "No account found associated with this email."
            email = None
    if request.method == "POST":
        input_code = request.POST['a_code']
        if input_code != code:
            message = "Code you entered didn't match!"
        if input_code == code:
            new_passwd = get_random_password()
            user = User.objects.get(email=email)
            user.set_password(raw_password=new_passwd)
            user.save()
            msg = "Your password has been set to <span class='text-danger font-weight-bold'>" + str(new_passwd) + "</span>"
            messages.success(request, msg)
            return redirect('/accounts/login/')
    if email == None:
        form = 'email'
    else:
        form = 'code'

    contex = {
        'email': email,
        'form': form,
        'message': message
    }
    return render(request, template_name, contex)


@login_required
def passwordChange_view(request):
    template_name = 'accounts/change-password.html'
    form = passwordChangeForm(request.user, request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = User.objects.get(email=request.user.email)
            user.set_password(raw_password=form.cleaned_data.get('new'))
            user.save()
            messages.success(request, user.get_full_name() + ', Your password has been updated successfully.')
            return redirect('/accounts/change-password/')
    contex = {
        'form': form
    }
    return render(request, template_name, contex)



@login_required
def update_view(request):
    try:
        account = Account.objects.get(user=request.user)
    except:
        account = None
    if account == None:
        messages.warning(request, 'Account not found!')
        return redirect('/accounts/')
    form = UpdateForm(account, request.POST or None, request.FILES or None, auto_id=False)
    if request.method == "POST":
        if form.is_valid():
            user = User.objects.get(email=request.user.email)
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name  = form.cleaned_data.get('last_name')
            user.save()
            account.about_me = form.cleaned_data.get('about_me')
            if form.cleaned_data.get('photo') != None:
                account.photo = form.cleaned_data.get('photo')
            print(form.cleaned_data.get('photo'))
            account.save()
            if os.path.exists(account.photo.path):
                drive_id = uploadToGoogleDrive(account.photo.path, 'PROFILE')
            if drive_id != "":
                account.drive_photo_link = "https://drive.google.com/thumbnail?id=" + str(drive_id)
                account.save()
            messages.success(request, 'Yahoo! Your information has been updated.')
            return redirect('/accounts/update/')
    template_name = 'accounts/edit.html'
    contex = {
        'form': form,
        'account': account
    }

    return render(request, template_name, contex)

@login_required
def profile_view(request):
    template_name = 'accounts/profile.html'
    try:
        account = Account.objects.get(user=request.user)
    except:
        return HttpResponseRedirect('/404-not-found/')

    post_list = Post.objects.all().filter(is_active=True).filter(account=account)
    paginator = Paginator(post_list, 5) # posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    contex = {
    	'account': account,
    	'posts': posts
    }
    return render(request, template_name, contex)




def activateAccount_view(request):
    template_name = 'accounts/activate.html'
    email = request.GET.get('email', None)
    code = None
    message = ""
    if email != None:
        qs = User.objects.filter(email=email)
        if qs.exists():
            account = Account.objects.get(user=User.objects.get(email=email))
            if not account.is_active:
                code = account.activation_code
            else:
                messages.success(request, "Your account is activated.")
                return redirect('/posts/')
        else:
            message = "No account found associated with this email."
            email = None
    if request.method == "POST":
        input_code = request.POST['a_code']
        if input_code != code:
            message = "Code you entered didn't match!"
        if input_code == code:
            account.is_active = True
            account.save()
            messages.success(request, "Congrats! Your account has been activated.")
            return redirect('/accounts/login/')
    if email == None:
        form = 'email'
    else:
        form = 'code'

    contex = {
        'email': email,
        'form': form,
        'message': message
    }
    return render(request, template_name, contex)

@login_required
def userLogout_view(request):
	next = request.GET.get('next', '/')
	if request.user.is_authenticated:
		logout(request)
		messages.success(request, "You have been logged out.")
	return redirect(next)

def userLogin_view(request):
    next = request.GET.get('next', '/')
    if request.user.is_authenticated:
        return redirect(next)
    template_name = 'accounts/login.html'
    contex = {}
    error  = ""
    if request.is_ajax() and request.method == "POST":
        email = request.POST['username']
        password = request.POST['password']
        if email == '' or password == '':
            error = 'Both fields are required.'
        else:
            qs = User.objects.filter(email=email).exists()
            if qs:
                user = User.objects.get(email=email)
                if not user.check_password(raw_password=password):
                    error = "Username or password incorrect"
            else:
                error = "Username or password incorrect"
        if error == '':
            user = authenticate(request, username=user.username, password=password)
            login(request, user)
            account = Account.objects.get(user=request.user)
            if account.is_active:
                error = ""
            else:
                logout(request)
                error = "Your account is not active."
            return HttpResponse(error)
        else:
            return HttpResponse(error)
    return render(request, template_name, contex)



def userCreate_view(request):
    next = request.GET.get('next', '/')
    if request.user.is_authenticated:
        return redirect(next)

    template_name = 'accounts/registration.html'
    contex = {}
    if request.method == "POST":
        name     	= request.POST['name']
        email    	= request.POST['email']
        password 	= request.POST['password']
        re_password = request.POST['re-password']
        errors      = registerValidation(name, email, password, re_password)
        if errors != "":
            contex = {'errors': errors}
        else:
            _name	 		= name.split()
            user    	    = User()
            user.first_name = _name[0]
            user.last_name  = ' '.join(_name[1:])
            user.username 	= usernameGenerator(email)
            user.email 		= email
            user.set_password(raw_password=password)
            user.save()
            account = Account()
            account.user = user
            account.save()
            # SEND EMAIL
            subject = "Account confirmation"
            body    = "Hello " + user.first_name + ", your account has been created successfully. We want to provide some recovery codes for you for future usage. Activation code: " + str(account.activation_code) + " Password recovery code: " + str(account.forgotpass_code) + " Account recovery code: " + str(account.recover_code) + ". Don't forget to save these codes. Thanks from FRIENDS community."
            try:

friends/src/templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Login{% endblock title %}

{% block slider %}
    <div style="margin-top: 160px!important"></div>
{% endblock slider %}
{% block post %}{% endblock post %}
{% block content %}
    <div class="container mb-5 mt-3 pb-5 min_height_400">
        <form class="form-horizontal" role="form" method="POST" action="">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="text-center mb-3">
                        <img src="{% static 'images/logo.png' %}" class="img-fluid" style="height: 80px;">
                    </div>
                    <div class="text-center">
                        <a href="{% url 'accounts:create' %}">
                            <h2 class="text-center btn btn-md btn-dark">
                                Registration
                            </h2>
                        </a>
                        <a href="{% url 'accounts:login' %}">
                            <h2 class="text-center active btn btn-md btn-danger">
                                Login
                            </h2>
                        </a>
                    </div>
                    <hr>
                </div>
            </div>


            <div class="row">
                <div class="col-md-3"></div>
                <div id="error" class="col-md-6"></div>
            </div>
            <div class="row">
                <div class="col-md-3 field-label-responsive">
                    <label for="name"></label>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                            <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                            <input type="text" name="username" class="form-control" id="username" placeholder="E-mail" autofocus>
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="row">
                <div class="col-md-3 field-label-responsive">
                    <label for="password"></label>
                </div>
                <div class="col-md-6">
                    <div class="form-group has-danger">
                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                            <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <button type="submit" id="submit" class="btn btn-sm btn-success"><i class="fa fa-user"></i> Login</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6 text-right">
                    <a href="{% url 'accounts:forgot-password' %}">Forgot password?</a><br>
                    <a href="{% url 'accounts:activate' %}">Activate account</a>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block js_files %}
    <script type="text/javascript">
        $(document).ready(function(){

            $('#submit').click(function(e){
                $('#ajaxLoader').show();
                e.preventDefault();
                if( $('#username').val() == '' || $('#password').val() == '' ){
                    $('#error').html("<div class='alert alert-danger'>Both fields are required.</div>");
                    $('#ajaxLoader').hide();
                }else{
                    $('#submit').html('<i class="fa fa-user"></i> Checking...');
                    $.ajax({
                        type: 'POST',
                        url: "{% url 'accounts:login' %}",
                        data:{
                            csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                            'username': $('#username').val(),
                            'password': $('#password').val(),
                        },
                        success: function(response){
                            if( response == "" ){
                                $('#submit').html('<i class="fa fa-user"></i> Logged in')
                                $('#ajaxLoader').hide();
                                window.location = "/posts/";
                            }else{
                                $('#error').html("<div class='alert alert-danger'>"+response+"</div>");
                                $('#submit').html('<i class="fa fa-user"></i> Login')
                                $('#ajaxLoader').hide();
                            }
                        },
                        error: function(){
                            $('#submit').html('<i class="fa fa-user"></i> Login')
                            $('#ajaxLoader').hide();
                            alert("Something went wrong. Please try again.")
                        }
                    });
                }
            });
        });
    </script>
{% endblock js_files %}

friends/src/templates/accounts/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ request.user.get_full_name }}{% endblock title %}

{% block slider %}
    <div style="margin-top: 100px!important"></div>
{% endblock slider %}

{% block post %}{% endblock post %}
{% block content %}
    <div class="container mb-5 mt-3 pb-5 min_height_400">
        <div class="row">
        	<div class="card col-md-4 bg-light" style="height: auto;">
	        	<div class="">
			        <img class="img-fluid" style="width: 100%; height: 160px" src="{% static 'images/services_parallax.jpg' %}" alt="...">
			    </div>
			    <div class="text-center" style="margin-top: -80px">
			    	{% if account.drive_photo_link != '' %}
                        <img class="mb-1 rounded-circle profile_photo" src="{{ account.drive_photo_link }}" alt="...">
                    {% else %}
                        <img class="mb-1 rounded-circle profile_photo" src="{% static 'images/blog_1.jpg' %}" alt="...">
                    {% endif %}
			    	<br>
			    	<h2>{{ request.user.get_full_name }}</h2>
			    	<h4 class="text-secondary">{{ request.user.email }}</h4>
                    <a class="text-success font-weight-bold" href="{% url 'accounts:change-password' %}">Change Password</a>
			    </div>
	        	<div class="card-body">
	        		<a href="{% url 'accounts:edit' %}" class="btn btn-sm btn-danger">Edit</a>
			    	<ul class="list-group">
					    <li class="list-group-item">
					    	<span class="alert-link">Username: </span>{{ request.user.username }}
					    </li>
                        <li class="list-group-item">
					    	<span class="alert-link">First Name: </span>{{ request.user.first_name }}
					    </li>
					    <li class="list-group-item">
					    	<span class="alert-link">Last Name: </span>{{ request.user.last_name }}
					    </li>
                        {% if account.about_me != '' %}
                            <li class="list-group-item text-center">
                                "{{ account.about_me }}"
                           </li>
                        {% endif %}
			 		</ul>
	        	</div>
	        </div> 
	        <div class="col-md-8">
            {% if posts %}
                {% for post in posts %}
                    <hr>
                    <article class="blog_post mt-2 bg-light p-2" style="border-radius: 10px">
                        <h3 class="blog_post_title mb-0"><a href="{{ post.account.get_profile_link }}">{{ post.account.user.get_full_name }}</a></h3>
                        <div class="blog_post_meta">
                            <small class="blog_post_author text-muted">Last edit: {{ post.updated|date }} | </small>
                            <small class="blog_post_category text-muted">{{post.likes}} likes | </small>
                            <small class="blog_post_comments text-muted">{{post.comments}} comments</small>
                        </div>
                        <div class="row">
                            {% if post.drive_photo1_link != "" %}
                                <div class="col-md">
                                    <img src="{{ post.drive_photo1_link }}" class="img-fluid post_img">
                                </div>
                            {% endif %}
                            {% if post.drive_photo2_link != '' %}
                                <div class="col-md">
                                    <img src="{{ post.drive_photo2_link }}" class="img-fluid post_img">
                                </div>
                            {% endif %}
                            {% if post.drive_photo3_link != '' %}
                                <div class="col-md">
                                    <img src="{{ post.drive_photo3_link }}" class="img-fluid post_img">
                                </div>
                            {% endif %}

                        </div>
                        <div class="blog_post_text">
                            <p>{{ post.content|truncatechars:160 }}</p>
                        </div>
                        <a href="{{ post.get_absolute_url }}" class="blog_post_link">read more
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                 width="13px" height="7px" viewBox="0 0 13 7" enable-background="new 0 0 13 7" xml:space="preserve">
                            <polygon id="arrow_poly_1" class="arrow_poly" fill="#FF4200" points="13,3.5 9,0 9,3 0,3 0,4 9,4 9,7 "/>
                            </svg>
                        </a>
                    </article>
                {% endfor %}
            {% else %}
                <h3 class="text-warning text-center mt-5">Nothing to show!</h3>
            {% endif %}

            <!-- PAGINATION -->    
            {% if posts.has_other_pages %}
                <div class="blog_nav text-center">
                    <ul class="mt-5">
                        {% if posts.has_previous %}
                            <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li><a class="disabled">&laquo;</a></li>
                        {% endif %}
                        {% for i in posts.paginator.page_range %}
                          {% if posts.number == i %}
                            <li class="active"><a href="#">{{ i }}</a></li>
                          {% else %}
                            <li><a  href="?page={{ i }}">{{i}}</a></li>
                          {% endif %}
                        {% endfor %}
                        {% if posts.has_next %}
                            <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li><a href="" class="disabled">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
            </div>
        </div>       
    </div>
{% endblock content %}

{% block js_files %}
    <script type="text/javascript">
       
    </script>
{% endblock js_files %}